Repository facebookincubator/contest, pull requests merged in 2020-04, with the labels that each got.

#84 Read job status entirely from the database
  docker/mysql/create_contest_db.sql
  pkg/api/api.go
  pkg/api/event.go
  pkg/job/eventmanager.go
  pkg/job/job.go
  pkg/job/request.go
  pkg/jobmanager/jobmanager.go
  pkg/jobmanager/start.go
  pkg/jobmanager/status.go
  pkg/storage/jobevents.go
  pkg/storage/jobs.go
  plugins/storage/rdbms/request.go
Labels: CLA Signed

#87 Allow passing custom server ID via server CLI
  cmds/contest/main.go
  pkg/api/api.go
  pkg/jobmanager/jobmanager.go
  tests/integ/jobmanager/common.go
Labels: CLA Signed

#89 Change lock timeout from 10s to 1m
  pkg/config/timeouts.go
  plugins/targetlocker/inmemory/inmemory.go
Labels: CLA Signed

#88 Add -wait flag to wait for completion after start command
  cmds/clients/contestcli-http/main.go
Labels: CLA Signed

#90 Reintroduce test statuses in status report
  pkg/jobmanager/jobmanager.go
  pkg/jobmanager/status.go
Labels: CLA Signed, bug

#91 Added CODEOWNERS
  CODEOWNERS
Labels: CLA Signed

#92 Added plugin information to errors in job events
  .travis/linters.sh
  README.md
  go.sum
  pkg/runner/job_runner.go
  pkg/runner/test_runner.go
  tests/integ/jobmanager/common.go
  tests/integ/test/testrunner_test.go
Labels: CLA Signed

#93 Make EndTime optional
  pkg/job/status.go
  pkg/jobmanager/status.go
Labels: CLA Signed

#94 Emit test event for plugin errors
  pkg/runner/event.go
  pkg/runner/test_runner.go
Labels: CLA Signed

#96 Simplify API for Job information storage and retrieval
  cmds/clients/contestcli-http/main.go
  pkg/job/eventmanager.go
  pkg/job/report.go
  pkg/job/reporter.go
  pkg/job/reporting.go
  pkg/job/request.go
  pkg/jobmanager/jobmanager.go
  pkg/jobmanager/start.go
  pkg/jobmanager/status.go
  pkg/storage/job.go
  pkg/storage/jobevents.go
  pkg/storage/jobs.go
  pkg/storage/report.go
  pkg/storage/request.go
  pkg/storage/storage.go
  pkg/test/parameter.go
  pkg/test/step_test.go
  tests/integ/jobmanager/common.go
Labels: CLA Signed

#97 Expose events that have no target associated
  pkg/job/status.go
  pkg/runner/job_status.go
  pkg/runner/test_runner.go
  plugins/teststeps/cmd/cmd.go
  tests/integ/jobmanager/common.go
  tests/integ/test/testrunner_test.go
Labels: CLA Signed, enhancement

#98 [plugins/reporters/noop] Noop.FinalReport should not return job.Report
  plugins/reporters/noop/noop.go
Labels: CLA Signed
